spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: bookmarks
    password: bookmarks
    url: jdbc:postgresql://localhost:5432/bookmarks
    driver-class-name: org.postgresql.Driver